# Properties configuration

# Logging configuration
logging.level=INFO
app.name=BOARetriever
app.version=1.0.0

# Basic information
boa.url=https://www.boa.aragon.es/cgi-bin/EBOA/BRSCGI?CMD=VERLST&BASE=BZHT&DOCS=1-200&SEC=OPENDATABOAJSON&OUTPUTMODE=JSON&SORT=-PUBL&SEPARADOR=&TITU=&SECC-C=I%2BO%2BII%2BO%2BIII%2BO%2BIV%2BO%2BV&SECC=&SUBS-C=&MATE-C=&NUMB=&RANG-C=&OLEY-C=&ALEY-C=&ORGA-C=&TEXT-C=&@PUBL-GE=20260622&@PUBL-LE=20260622&FDIS-C=